# Generated by Django 5.2.18 on 2026-10-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['facility_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='followup.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('visit_type', models.CharField(choices=[('routine', 'Routine'), ('follow_up', 'Follow-up'), ('unscheduled', 'Unscheduled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='followup.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['facility', 'last_name', 'first_name'], name='followup_pa_facilit_08dc31_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('facility', 'patient_number'), name='unique_patient_number_per_facility'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='followup_vi_patient_f5e9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['next_appointment_date'], name='followup_vi_next_ap_bccffb_idx'),
        ),
    ]
