# Generated by Django 5.2.18 on 2026-10-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_at', models.DateTimeField()),
                ('note', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_contacts', to='followup.patient')),
            ],
            options={
                'ordering': ['-contacted_at', '-id'],
                'indexes': [models.Index(fields=['patient', '-contacted_at'], name='followup_fo_patient_e557b3_idx')],
            },
        ),
    ]
